### ISSUE TITLE
Why do you need Jquery 2.0.3 as dependency? why not 1.11.x?

### ISSUE THREAD

**Issue by mitakora** [angular-macgyver/macgyver-datepicker#5]
Hello, 

I am using this datepicker in an angular app, though I need to give support to IE 8+. 
After checking your code I still  don't understand why in the bower.json you have JQuery version ~2.0.3,  why not use JQuery 1.11.x?, in any case jquery-ui dependency is ~1.10.3.

Can you downgrade JQuery dependency?

Monica

**Comment by adrianlee44** [comment]
There's actually no reason that it can't be jQuery 1.11.x. Let me up change the dependencies.

**Comment by mitakora** [comment]
Those are great news!!.

Let me know when I can update my bower json and get the library with the new dependencies.

Thanks

Monica

**Comment by adrianlee44** [comment]
Just updated the package to v0.5.2 with the following dependencies,
```
"dependencies": {
    "angular": ">=1.2.0",
    "jquery": ">=1.11.0",
    "jquery-ui": "~1.11.0"
  },
```

Let me know if this works.

**Comment by adrianlee44** [comment]
This should be fixed. Reopen if it's still an issue.

**Comment by mitakora** [comment]
Hello, 

I tested the new version but it didn't work for me. I have a dependency on Jquery-ui ~1.10.x thus I am having a conflict when installing all the libraries.
 
This dependency was working with your previous configuration of Jquery-ui.

Let me know if is possible to keep Jquery-ui depedency as before.

Thanks.

**Comment by adrianlee44** [comment]
Ah, I see. Let me update that and do another release.

**Comment by adrianlee44** [comment]
Updated to v0.5.3 with jquery-ui requirement as >=1.10.0

**Comment by mitakora** [comment]
Working like a charm!!

Thank you
